$$
\newcommand{\fudm}[2]{\frac{\mathrm{D} #1}{\mathrm{D} #2}}
\newcommand{\pad}[2]{\frac{\partial #1}{\partial #2}}
\newcommand{\ppad}[2]{\frac{\partial^2 #1}{\partial #2^2}}
\newcommand{\ppadd}[3]{\frac{\partial^2 #1}{\partial #2 \partial #3}}
\newcommand{\nnabla}{\nabla^2}
\newcommand{\eps}{\epsilon}
\newcommand{\vdetail}[1]{\vb{#1}=\begin{pmatrix}#1_1\\#1_2\\#1_3\end{pmatrix}}
\newcommand{\vb}[1]{\mathbf{#1}}
\newcommand{\va}[1]{\vec{#1}}
\newcommand{\tb}[1]{\underline{\underline{\mathbf{#1}}}}
\newcommand{\fud}[2]{\frac{\mathrm{d} #1}{\mathrm{d} #2}}
$$


# Math Refresher

In this course we work with vectors, matrices, and tensors. Vectors can be written as row and column vectors, this is important as it defines how they multiply with matrices and tensors. A column vector is written as a vertical tuple, while the row vector is a horizontal tuple:

$$\va{a}=\vb{a}=\left(
\begin{array}{c}
a_1\\
a_2\\
a_3
\end{array}\right)=(a_1,a_2,a_3)^T$$

The $^T$ sign transposes the vector or matrix/tensor, rows become columns and vice versa. Please note the different ways we can write the vectors; in this course we'll mostly use the bold face style, i.e. $\vb{a}$.

## Scalar Product
The *scalar product* or *dot product* is a product between two vectors where the same components are multiplied and then summed. The result is related to length and $\cos$ of the angle of the two vectors.

\begin{eqnarray}
\vb{a}\cdot\vb{b}=|\vb{a}|\,|\vb{b}|\,\cos(\vb{a},\vb{b})&=&a_1 b_1 + a_2 b_2 +a_3 b_3\\
&=&\sum a_i b_i := a_i b_i
\end{eqnarray}

The last expression is a definition, the so-called *Einstein summation convention*. In this course we will only use it for identical subscripts in products. Then it states, that we automatically sum over identical subscripts, the summation sign is not written anymore. The reason is that we can conveniently write lengthy products with less mathematical symbols.

Having calculated the scalar product of two vectors, we can easily obtain the angle between the vectors through:

\begin{equation}
\cos(\vb{a},\vb{b})=\frac{\vb{a}\cdot\vb{b}}{|\vb{a}|\,|\vb{b}|}
\end{equation}
<p>
<div class="Detail"> **Homework:** <p>
Write above equation using Einstein summation convention.</div>
<p>

Below you find how to define column and row vectors in Python. We will always use two packages which work hand in hand together. The first package is called `numpy` (short for NUMerical PYthon) which provides functions for vectors and matrices including all kinds of linear algebra tools. The second package is `scipy` (SCIentific PYthon) which has all the mathematical functions numerical and work conveniently with the vectors and matrices defined with `numpy`.

In [25]:
import numpy as np     #Numpy contains the versatile array classfrom scipy

print("This is a row vector")
a = np.array([5,1,2]) 
print("a={0}".format(a))

This is a row vector
a=[5 1 2]


In [26]:
print("This is a column vector")
b = np.array([[1],[2],[3]])
print("b={0}".format(b))

This is a column vector
b=[[1]
 [2]
 [3]]


Row and column vectors in Matlab are very different while Python does not really care about it.

In [5]:
print ("Dot product of two row vectors")
print ("a . a = {0}".format(a.dot(a)))
print ("which is the same as")
print ("a . a = {0}".format(np.dot(a,a)))
print ("which is the same for two column vectors")
print ("b . b = {0}".format(np.vdot(b,b)))  #For column vectors we need to use vdot()

Dot product of two row vectors
a . a = 30
which is the same as
a . a = 30
which is the same for two column vectors
b . b = 14


In [6]:
print ("Now we define two vectors and show that their angle is 90 degrees")
c = np.array([2,0])
d = np.array([0,2])
print (c)
print (d)

Now we define two vectors and show that their angle is 90 degrees
[2 0]
[0 2]


In [7]:
myangle = math.acos(np.dot(c,d)/(np.linalg.norm(c)*np.linalg.norm(d)))
print ("Angle between (c,d) = {} degree".format(myangle*180./math.pi))

Angle between (c,d) = 90.0 degree


Thus the important functions to remember are the initialization using
`np.array([`$a_1$ `, ` $a_2$ `, ` $a_3$`])`, the scalar product `np.dot(a,b)`, and the norm using `np.linalg.norm(a)`.

## Vector Product
The vector product (or sometimes called cross product) leads to a vector $\vb{c}$ which is perpendicular to $\vb{a}$ and $\vb{b}$:
$$\vb{a} \times \vb{b}=\vb{c}\quad .$$

It's length is given by 
$$|\vb{a} \times \vb{b}|=|\vb{a}|\,|\vb{b}|\,\sin(\vb{a},\vb{b})\,.$$

A coordinate system where $\vb{a}$ and $\vb{b}$ are not parallel
$$(\vb{a},\vb{b},\vb{a} \times \vb{b})$$ 
is right handed.

A few rules to keep in mind:

$$\vb{a} \times (\vb{b} \times \vb{c})\neq (\vb{a} \times \vb{b}) \times \vb{c}$$

$$\vb{a} \times \vb{b} = - \vb{b} \times \vb{a}$$

$$\vb{a} \times \vb{a} = \vb{0}$$

$$(\vb{a} + \vb{b}) \times \vb{c}= \vb{a} \times \vb{c} + \vb{b} \times \vb{c}$$

If $\vb{a} \times \vb{b} = \vb{0}$ then $\vb{a}=\vb{0}$, $\vb{b}=\vb{0}$, and/or $\vb{a} \parallel \vb{b}$ .

But how do we calculate the vector product?
$$\left(a_1,a_2,a_3\right) \times \left(b_1,b_2,b_3\right)=\\
\left(\begin{array}{c}
a_2 b_3 - a_3 b_2\\
a_3 b_1 - a_1 b_3\\
a_1 b_2 - a_2 b_1
\end{array}\right)^T$$

I have difficulty remembering the order of the variables, an eays way out is to remember that the vector product is the determinant of a matrix with 3 rows composed out of the unit vectors $(\vb{e_1},\vb{e_2},\vb{e_3})$, the first, and the second vector:
$$\left|\begin{array}{c c c}
\vb{e_1}&\vb{e_2}&\vb{e_3}\\
a_1&a_2&a_3\\
b_1&b_2&b_3
\end{array}\right|=
\left(\begin{array}{c}
a_2 b_3 - a_3 b_2\\
a_3 b_1 - a_1 b_3\\
a_1 b_2 - a_2 b_1
\end{array}\right)$$.

The cross product is calculated with the function `np.cross(a,b)` where $a$ and $b$ are two row or column vectors.

In [27]:
a = np.array([1,0,0])
b = np.array([0,1,0])
print ("We calculate the cross product")
print ("a = {0}".format(a)+", b = {0}".format(b))
print ("a x b = {0}".format(np.cross(a,b)))

We calculate the cross product
a = [1 0 0], b = [0 1 0]
a x b = [0 0 1]


## Matrix and Matrix or Inner Product
A matrix has row and columns and each position of the matrix is addressed with a tuple $(i,j)$, where $i$ refers to the rows and $j$ to the columns. This is an example of a 3x3 matrix:

$$\tb{A}=A_{ij}=\left(
\begin{array}{ccc}
A_{11}&A_{12}&A_{13}\\
A_{21}&A_{22}&A_{23}\\
A_{31}&A_{32}&A_{33}
\end{array}\right)$$

The product of two matrices at position $(i,j)$ in the resulting matrix is the summation of the products of the $i$-th row of the first matrix and the $j$-th column of the second matrix. As an example let two 3x3 matrices $\tb{A}$ and $\tb{B}$ multiply and write down the component (2,1) of the resulting matrix:

$$\tb{A}\,\tb{B}=
\left(\begin{array}{ccc}
A_{11}&A_{12}&A_{13}\\
A_{21}&A_{22}&A_{23}\\
A_{31}&A_{32}&A_{33}
\end{array}\right) 
\left(\begin{array}{ccc}
B_{11}&B_{12}&B_{13}\\
B_{21}&B_{22}&B_{23}\\
B_{31}&B_{32}&B_{33}
\end{array}\right)=
\left(\begin{array}{ccc}
...&...&...\\
A_{21}B_{11}+A_{22}B_{21}+A_{23}B_{31}&...&...\\
...&...&...
\end{array}\right)$$

The identity matrix is 

$$\tb{I}=
\left(\begin{array}{ccc}
1&0&0\\
0&1&0\\
0&0&1
\end{array}\right)=\delta_{ij}$$

The transpose operator switches rows with columns, i.e. transforms $(i,j)\rightarrow(j,i)$. As an example we transpose A:


$$\tb{A}^T=\left(\begin{array}{ccc}
A_{11}&A_{21}&A_{31}\\
A_{12}&A_{22}&A_{32}\\
A_{13}&A_{23}&A_{33}
\end{array}\right) $$


In [28]:
print ("define matrix A")
A = np.array([[1,2,3],[3,2,1],[-1,1,-1]])
print (A)
print ("B is a matrix filled with ones:")
B = np.array([[1,0,0],[0,1,0],[0,0,1]])
print (B)

print ("The product of AB =\n {0}".format(A.dot(B)))

define matrix A
[[ 1  2  3]
 [ 3  2  1]
 [-1  1 -1]]
B is a matrix filled with ones:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
The product of AB =
 [[ 1  2  3]
 [ 3  2  1]
 [-1  1 -1]]


## Inner Product between a vector and a matrix
The inner or matrix product is generated of the product of the *row* of the first matrix and the *columnn* of the second matrix. Thus multiplying a vector with a matrix can be either a row vector, $\vb{a}$, with a matrix, $\tb{A}$, thus $\vb{a} \tb{A}$ or a matrix multiplied with a column vector, $\vb{b}$, thus $\tb{A} \vb{b}$. The resulting vector keeps the shape of the initial vector, i.e. a row or column vector. The product is not communitative.

$$\vb{a} \tb{A} = \left(a_1,a_2,a_3\right)\,
\left(\begin{array}{ccc}
A_{11}&A_{12}&A_{13}\\
A_{21}&A_{22}&A_{23}\\
A_{31}&A_{32}&A_{33}
\end{array}\right)=\left(
\begin{array}{c}
a_1 A_{11} + a_1 A_{21} + a_1 A_{31}\\
a_2 A_{12} + a_2 A_{22} + a_2 A_{32}\\
a_3 A_{13} + a_3 A_{23} + a_3 A_{33}\\
\end{array}
\right)^T$$

$$ \tb{A} \vb{b}= 
\left(\begin{array}{ccc}
A_{11}&A_{12}&A_{13}\\
A_{21}&A_{22}&A_{23}\\
A_{31}&A_{32}&A_{33}
\end{array}\right)
\left(\begin{array}{c}
b_1\\b_2\\b_3
\end{array}\right)
=\left(
\begin{array}{c}
b_1 A_{11} + b_2 A_{12} + b_3 A_{13}\\
b_1 A_{21} + b_2 A_{22} + b_3 A_{23}\\
b_1 A_{31} + b_2 A_{32} + b_3 A_{33}\\
\end{array}
\right)$$


Next we have a look how matrix-vector multiplications are done with Python:  

In [30]:
A = np.array([[1,2,3],[3,2,1],[-1,1,-1]])
b = np.array([[1],[2],[3]]) #column vector

print ("A b = {0}".format(A.dot(b))) #matrix times a column vector

A b = [[14]
 [10]
 [-2]]


<div class="Detail"> **Homework:**<p>
1. Write the multiplication $\vb{a} \tb{A}$ and $\tb{A} \vb{b}$ using Einstein summation convention. Hint: Write it first as a sum using the $\sum$-symbol.<p>
2. What happens in Python when you multiply a column vector to the left side of a 3x3 matrix?
</div>